name: AutoBOM

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  autobom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hardware repo
        uses: actions/checkout@v4

      - name: Run AutoBOM
        uses: opulo-inc/autobom@main